story = input("Please enter a story")
story = story.replace(" the ", " ermahgerd ")
story = story.replace(" The ", " ermahgerd ")
story = story.replace(" a ", " ayyyyyy ")
story = story.replace(" A ", " ayyyyyy ")
story = story.replace(".", ".*BEEP*")
print(story)
